In [1]:
import numpy as np
#This following is so that this will work with Latex, see
#http://bkanuka.com/articles/native-latex-plots/
import matplotlib as mpl
mpl.use('pgf')

In [2]:
def figsize(scale):                                 # I think scale is the size you want it on the page
    fig_width_pt = 433.62001                        # Get this from LaTeX using \the\textwidth
    inches_per_pt = 1.0/72.0                        # Convert pt to inch
    golden_mean = (np.sqrt(5.0)-1.0)/2.0            # Aesthetic ratio (you could change this)
    fig_width = fig_width_pt*inches_per_pt*scale    # width in inches
    fig_height = fig_width*golden_mean              # height in inches
    fig_size = [fig_width,fig_height]
    return fig_size

pgf_with_lualatex = {                      # Setup matplotlib to use latex for output
    "pgf.texsystem": "lualatex",           # Change this if using xetex or luatex
    "text.usetex": True,                   # Use LaTeX to write all text
    "pgf.rcfonts": False,
    #Fonts
    "font.family": "serif",                # Get from the pdf font function on the doc
    "font.serif": "Computer Modern Roman",      
    #"font.sans-serif": "Computer Modern Sans serif",
    #"font.serif": [],      
    "font.sans-serif": [],
    "font.monospace": [], # Blank entries should cause plots to inherit fonts from the document
    #Text size
    "font.size": 11,# Document default is 11pt font.
    #"text.fontsize": 11,
    "axes.labelsize": 11,
    "legend.fontsize": 8,               # Make the legend/label fonts a little smaller
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    ##Axis
    #"axes.labelpad": 2,     # space between label and axis 
    "figure.figsize": figsize(1.0),     # default fig size of 1.0 textwidth
    #Packages
    "pgf.preamble": [
        r"\usepackage[utf8x]{inputenc}",    # use utf8 fonts becasue your computer can handle it :)
        r"\usepackage[T1]{fontenc}",        # plots will be generated using this preamble
        r"\usepackage{amsmath}",  #need to add math or the ^ won't work
        r"\usepackage{amssymb}"]
    }

mpl.rcParams.update(pgf_with_lualatex)

In [3]:
import pandas as pd
import matplotlib.pyplot as pp
import seaborn as sns

In [4]:
%matplotlib inline
pp.style.use('seaborn-ticks')

In [5]:
# Load inputs to calculation from .csv files.
#asym_corr = pd.read_csv('data/al_asym_corrections_thesis_high_stat.csv')
#bk_frac = pd.read_csv('data/al_background_fractions_thesis_high_stat_avg.csv')
test_data = pd.read_csv('data/test_mod1.csv')

In [6]:
test_data

   asym2  asym1  asym3  asym4  asym5
0    1.0    2.0    1.0    3.0    1.0
1    0.5    0.0    0.5    0.5    0.5

In [7]:
samples = 10

In [8]:
name = np.full((len(test_data.columns),len(test_data.columns)), list(test_data.columns), dtype='<U16')

In [9]:
name

array([['asym2', 'asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'asym4', 'asym5']], dtype='<U16')

In [10]:
for i in range(len(name)):
    name[i][i] = 'rand_' + name[i][i]

In [11]:
name

array([['rand_asym2', 'asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'rand_asym1', 'asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'rand_asym3', 'asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'rand_asym4', 'asym5'],
       ['asym2', 'asym1', 'asym3', 'asym4', 'rand_asym5']], dtype='<U16')

In [12]:
def calc_asym(df, name_map):
    return df[name_map[0]] + df[name_map[1]] + df[name_map[2]] + df[name_map[3]] + df[name_map[4]]

In [13]:
data = pd.DataFrame()

In [14]:
for label in test_data.columns:
    data[label] = test_data[label][0]*np.ones(samples)
    if test_data[label][1] != 0.0:
        data['rand_' + label] = np.random.normal(test_data[label][0], test_data[label][1], samples)
    else:
        data['rand_' + label] = data[label]

In [15]:
data

,asym2,rand_asym2,asym1,rand_asym1,asym3,rand_asym3,asym4,rand_asym4,asym5,rand_asym5
0,1.0,0.564304,2.0,2.0,1.0,0.283336,3.0,3.330797,1.0,1.643812
1,1.0,1.488921,2.0,2.0,1.0,1.367667,3.0,3.561473,1.0,-0.025936
2,1.0,0.564868,2.0,2.0,1.0,0.944703,3.0,2.555067,1.0,1.050438
3,1.0,1.261011,2.0,2.0,1.0,0.721414,3.0,2.929843,1.0,0.013633
4,1.0,0.877768,2.0,2.0,1.0,1.508537,3.0,3.409132,1.0,1.169326
5,1.0,1.624840,2.0,2.0,1.0,1.814334,3.0,2.829091,1.0,1.590065
6,1.0,0.716696,2.0,2.0,1.0,0.611761,3.0,2.176566,1.0,1.361701
7,1.0,0.608845,2.0,2.0,1.0,1.346435,3.0,3.795477,1.0,1.571825
8,1.0,0.885719,2.0,2.0,1.0,0.617505,3.0,2.991968,1.0,0.774538
9,1.0,1.733767,2.0,2.0,1.0,1.320449,3.0,3.614596,1.0,1.695153

In [16]:
len(data)

10

In [16]:
results = pd.DataFrame()

In [17]:
def calc_all(data, results, name_map):
    for i in range(len(name)):
        results[np.diag(name)[i]] = calc_asym(data, name_map[i])
    results['apv'] = calc_asym(data, np.diag(name))
    results['cv'] = calc_asym(data, test_data.columns)

In [18]:
%timeit calc_all(data, results, name)

4.28 ms ± 272 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [19]:
results

   rand_asym2  rand_asym1  rand_asym3  rand_asym4  rand_asym5       apv   cv
0    7.726157         8.0    7.917954    7.520551    8.178407  7.343068  8.0
1    8.115935         8.0    7.925916    7.953504    9.099443  9.094799  8.0
2    8.608442         8.0    6.952442    7.885801    7.898209  7.344893  8.0
3    7.924946         8.0    7.784257    7.833558    9.217079  8.759840  8.0
4    8.221247         8.0    7.492297    7.722789    7.428504  6.864838  8.0
5    8.742182         8.0    8.153975    7.767501    7.489433  8.153091  8.0
6    7.268778         8.0    7.754995    8.687692    8.265627  7.977091  8.0
7    7.810703         8.0    8.546931    7.709520    8.232755  8.299910  8.0
8    7.451928         8.0    8.322656    9.153391    8.335722  9.263699  8.0
9    8.132182         8.0    8.562681    7.726234    8.340601  8.761698  8.0

In [21]:
p = Pool(processes=len(name))
test = p.map(calc_asym, [name])
p.close()

In [20]:
# Extra

In [ ]:
test = pd.read_csv('data/mc_apv_inputs_thesis.csv', header=None, index_col=0)

In [ ]:
test = np.transpose(test)

In [ ]:
test

In [ ]:
test.columns[0]

In [17]:
test = {}

In [18]:
test

{}

In [19]:
test = {}

In [24]:
label = 'rand_' + 'f_Zn'

In [25]:
label

'rand_f_Zn'

In [27]:
label[5:]

'f_Zn'

In [23]:
data = pd.read_csv('mc_apv_extraction_output.csv', index_col=0)

In [26]:
data.loc['A_pv']

mean    1.924292
std     0.156940
Name: A_pv, dtype: float64

In [27]:
data.sort_values(by=['std'], ascending=False)

                 mean           std
A_pv         1.924292  1.569404e-01
A_inelastic  1.923467  1.207990e-01
A_quasi      1.923602  6.125668e-02
f_quasi      1.924155  3.705269e-02
A_Zn         1.923559  3.060305e-02
A_Mg         1.923638  2.981718e-02
A_2211keV    1.923619  2.435229e-02
A_bias       1.923577  2.402865e-02
A_2990keV    1.923579  1.733531e-02
f_GDR        1.923679  1.709308e-02
P            1.923695  1.423994e-02
A_trans      1.923609  1.409013e-02
A_nonlin     1.923583  1.152525e-02
R_acc        1.923579  1.064570e-02
A_GDR        1.923587  9.115989e-03
A_Cu         1.923583  9.015348e-03
A_1014keV    1.923593  7.521151e-03
A_0844keV    1.923589  5.010231e-03
A_2735keV    1.923591  3.499300e-03
A_7228keV    1.923591  3.444139e-03
f_inelastic  1.923626  3.426215e-03
A_bb         1.923585  3.201138e-03
R_det        1.923587  3.105936e-03
A_5430keV    1.923586  2.937703e-03
A_beam       1.923587  2.242951e-03
A_7477keV    1.923594  1.918378e-03
f_beamline   1.923593  1.665888e-03
f_pions      1.923592  1.665374e-03
A_4812keV    1.923592  1.504433e-03
A_5668keV    1.923590  1.499848e-03
...               ...           ...
A_Si         1.923590  1.128315e-03
A_4580keV    1.923590  1.108108e-03
f_1014keV    1.923590  7.471566e-04
A_Fe         1.923587  7.221504e-04
f_2990keV    1.923590  5.384193e-04
f_7228keV    1.923590  5.251487e-04
f_7477keV    1.923590  4.781342e-04
f_Zn         1.923591  4.580085e-04
f_844keV     1.923590  3.414289e-04
A_Mn         1.923590  2.997897e-04
A_Ti         1.923590  2.137580e-04
f_5430keV    1.923590  1.910394e-04
f_Mg         1.923590  1.786749e-04
f_2735keV    1.923590  1.360664e-04
f_5668keV    1.923590  1.007128e-04
f_Cu         1.923590  9.334590e-05
f_4812keV    1.923590  7.887581e-05
f_4580keV    1.923590  7.091343e-05
f_Mn         1.923590  5.001556e-05
f_Ti         1.923590  1.950965e-05
f_Fe         1.923590  4.923842e-06
f_Cr         1.923590  4.615116e-06
f_Si         1.923590  3.634667e-06
R_q2         1.923590  2.824274e-11
R_rc         1.923590  2.824274e-11
A_raw        1.923590  2.824274e-11
A_neutral    1.923590  2.824274e-11
A_bcm        1.923590  2.824274e-11
A_pions      1.923590  2.824274e-11
CV           1.923590  2.824274e-11

[63 rows x 2 columns]